version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - TZ=Europe/Moscow
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server-image
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_DATASOURCE_USERNAME=root
      - POSTGRES_DATASOURCE_PASSWORD=root
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver


  db:
    image: postgres:15.3-alpine
    container_name: shareit-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root