DROP TABLE IF EXISTS users, items, bookings, comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255)        NOT NULL,
    email     VARCHAR(512) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name        VARCHAR(255) NOT NULL,
    owner_id         BIGINT REFERENCES users (id) ON DELETE CASCADE,
    item_description VARCHAR(512) NOT NULL,
    available        BOOLEAN,
    request_id       BIGINT
);

CREATE TABLE IF NOT EXISTS bookings
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time     TIMESTAMP WITHOUT TIME ZONE,
    end_time       TIMESTAMP WITHOUT TIME ZONE,
    item_id        BIGINT REFERENCES items (id) ON DELETE CASCADE,
    booker_id      BIGINT REFERENCES users (id) ON DELETE CASCADE,
    booking_status VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text    VARCHAR(1012),
    item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE
);