DROP TABLE IF EXISTS users, items, bookings, comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255)                            NOT NULL,
    email     VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name        VARCHAR(255)                            NOT NULL,
    owner_id         BIGINT,
    item_description VARCHAR(512)                            NOT NULL,
    available        BOOLEAN,
    request_id       BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT fk_item FOREIGN KEY (owner_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time     TIMESTAMP WITHOUT TIME ZONE,
    end_time       TIMESTAMP WITHOUT TIME ZONE,
    item_id        BIGINT,
    booker_id      BIGINT,
    booking_status VARCHAR(10),
    CONSTRAINT pk_booking PRIMARY KEY (booking_id),
    CONSTRAINT fk_booking FOREIGN KEY (item_id) REFERENCES items (item_id),
    CONSTRAINT fk_booking_second FOREIGN KEY (booker_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR(1012),
    item_id    BIGINT,
    user_id    BIGINT,
    created    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id),
    CONSTRAINT fk_comment FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_second FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);